In [1]:
!pip install scikit-learn

In [2]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
wine_quality = fetch_ucirepo(id=186) 
  
# data (as pandas dataframes) 
X_df = wine_quality.data.features 
y_df = wine_quality.data.targets 
  
# metadata 
#print(wine_quality.metadata) 
  
# variable information 
#print(wine_quality.variables) 


In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Starting the exploratory data analysis. To perform standard pandas operations, I need to convert X and y (which are the features and targets of the dataset, respectively) into pandas DataFrames. I plan to check columns to understand datatypes, value ranges, find possible missing values, the correlation between features, and create relevant data visualizations.

In [9]:
winedf = pd.concat([X_df, y_df], axis=1)

In [15]:
winedf.head()

#winedf.columns

#winedf.isnull().sum()

#winedf.describe()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

#Great no null values! So I dont have to worry about dropping any rows and my chances of missing data or data that was inputted wrong is lower.

#These data types seem to be correct considering most of htem are percentages in decimal form float64 for would be the best Dtype for them. I also see the quality is int64 I beleive this column is the quality ratings given to each wine which would be whole numbers.

In [17]:
wine_quality.data

{'ids': None,
 'features':       fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
 0               7.4              0.70         0.00             1.9      0.076   
 1               7.8              0.88         0.00             2.6      0.098   
 2               7.8              0.76         0.04             2.3      0.092   
 3              11.2              0.28         0.56             1.9      0.075   
 4               7.4              0.70         0.00             1.9      0.076   
 ...             ...               ...          ...             ...        ...   
 6492            6.2              0.21         0.29             1.6      0.039   
 6493            6.6              0.32         0.36             8.0      0.047   
 6494            6.5              0.24         0.19             1.2      0.041   
 6495            5.5              0.29         0.30             1.1      0.022   
 6496            6.0              0.21         0.38             0.8     

I was having trouble finding the color column with the code given by the UCI to call the data into python. I believe they made a new datasheet to remove the color column. However, for our assignment I have to hot code a catergorical variable and color is the only catergorical column. After running "wine_quality.data" I was able to find the column under "original" so my next step it to pull out the orginal datset and work on that moving forward. 

In [20]:
original_data = wine_quality.data['original']
original_data.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality color  
0      9.4        5   red  
1      9.8        5   red  
2      9.8        5   red  
3      9.8        6   red  
4      9.4        5   red

In [22]:
original_data.dtypes

fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
color                    object
dtype: object

In [60]:
original_data.head

<bound method NDFrame.head of       fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020  

In [ ]:
#time for wine colored graphs

plt.scatter(original_data['quality'], original_data['pH'], color = 'maroon')
plt.title('relation of pH with wine')
plt.xlabel('quality')
plt.ylabel('pH')
plt.legend()
plt.show()

In [ ]:
plt.title('Fixed Acidity vs Quality')
plt.xlabel('Fixed Acidity')
plt.ylabel('Quality')
plt.scatter(original_data['fixed_acidity'], original_data['quality'], color = 'magenta')
plt.show()

In [ ]:
plt.bar(data['quality'], data['alcohol'], color = 'pink')
plt.title('relation of alcohol to wine')
plt.xlabel('quality')
plt.ylabel('alcohol')
plt.legend()
plt.show()

In [ ]:
import seaborn as sns

In [62]:
#Spliting data in two like above

X = original_data.drop(columns=['quality'])  # Features
y = original_data['quality']

print(X.columns)

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'color'],
      dtype='object')


In [64]:
X.shape, y.shape

((6497, 12), (6497,))

In [ ]:
fig = plt.figure(figsize = (10,6))
sns.barplot(X, palette = 'Reds')

Ran into a ValueError when trying to create a correlation matrix so I am going to bring back the features list from the updated dataset because that does not include the color and target(quality) columns.

In [ ]:
corr = winedf.corr()
print(corr)

The corrrelation matrix is great to know when proceeding but i belive I will be able to absorb the information better if visualize it.

In [ ]:
plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.show()

From the correlation matrix and plot we can see which features have strong correlation and which features do not. I belive this will be inportant in the future when determining which columns are the most revelant. The alcohol content of the wine has a high correlation with the wine quality. This is important to note because wine quality is what we will working closely with. Some features have negative correlation like density. I plan to remove the features with the most correlation to quality to eliminate some noise if I need to.

In [ ]:
sns.pairplot(original_data, hue='color')

Prediction: I'm not seeing any strong linear relationships in my exploratory graphs. That the random forest will have higher accuracy and F1 scores.

Okay now that I have done all of my exploratory analysis I feel confident to move on to the next step. During my exploratory analysis I did not find any missing values, I know the dtypes of all my columns, and I was able to see the correlation beetween categories. Next I will create a sklearn pipeline that includes preprocessing steps such as scaling and one hot encoding of categorical variable. 

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [66]:
x_train, x_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    test_size=0.3,
                                                    random_state=42)

In [68]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4547, 12), (1950, 12), (4547,), (1950,))

In [ ]:
x_test

In [50]:
num_cols = ['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol']
cat_cols = ['color']

# Create the ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),  # Scale numerical features
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)  # One-hot encode categorical features
    ])


The first model I will train will be Logicregression

In [74]:
pipe = Pipeline(steps=[
    ('preprocessor', preprocessor), ('model', LogisticRegression())])

In [ ]:
pipe.fit(x_train, y_train)


# calculating the training and testing accuracies
print("Training accuracy :", pipe.score(x_train, y_train))
print("Testing accuracy :", pipe.score(x_test, y_test))

y_pred = pipe.predict(x_test)

print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

From the results of the test above I'm going to proceed with removing some column/features to reduce noise and hopefully help with the overfitting of the model above

In [ ]:
X.columns

In [ ]:
#columnsdrop = ['fixed_acidity','residual_sugar', 'total_sulfur_dioxide', 'pH', 'sulphates']
#X_df = X.drop(columns=columnsdrop)

#redoing the test/train split
#x_train, x_test, y_train, y_test = train_test_split(X_df, y, test_size=0.3, random_state=42)

In [ ]:
#num_cols1 = ['volatile_acidity', 'citric_acid',
      # 'chlorides', 'free_sulfur_dioxide', 'density','alcohol']
#cat_cols = ['color']

#preprocessor1 = ColumnTransformer(
  #  transformers=[
 #       ('num', StandardScaler(), num_cols1),  # Scale numerical features
  #      ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)  # One-hot encode categorical features
  #  ])

#pipe = Pipeline(steps=[
 #   ('preprocessor1', preprocessor1), ('model', LogisticRegression())])

#pipe.fit(x_train, y_train)



#print("Training accuracy :", pipe.score(x_train, y_train))
#print("Testing accuracy :", pipe.score(x_test, y_test))
#
#y_pred = pipe.predict(x_test)

#print("Classification Report:")
#print(classification_report(y_test, y_pred))

# Confusion matrix
#print("Confusion Matrix:")
#print(confusion_matrix(y_test, y_pred))

The results actually seem to be worse. I believe the results are low because the linear relationships between the features and quality are weak as I predicted above. I will comment that attempt out and will move on to randomforest.

In [56]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

In [70]:
pipeline.fit(x_train, y_train)
y_pred = pipeline.predict(x_test)

# Calculate and print the training and testing accuracies
print("Training accuracy :", pipeline.score(x_train, y_train))
print("Testing accuracy :", pipeline.score(x_test, y_test))

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Training accuracy : 1.0
Testing accuracy : 0.6743589743589744
Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       0.67      0.12      0.20        69
           5       0.67      0.74      0.71       613
           6       0.67      0.74      0.70       894
           7       0.69      0.54      0.61       315
           8       0.94      0.33      0.48        49
           9       0.00      0.00      0.00         1

    accuracy                           0.67      1950
   macro avg       0.52      0.35      0.39      1950
weighted avg       0.68      0.67      0.66      1950

Confusion Matrix:
[[  0   0   4   5   0   0   0]
 [  1   8  42  18   0   0   0]
 [  0   3 455 148   7   0   0]
 [  0   1 172 666  55   0   0]
 [  0   0   4 140 170   1   0]
 [  0   0   0  19  14  16   0]
 [  0   0   0   1   0   0   0]]


/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Instantly i can see that these results are a lot better than the logicregression. I'm wondering if the results would be even better excluding some feature so theres less potential for overfitting. To figure out how to make this model a little more accurate I will run a grid search to improve the result. Report the best set of parameters. 

In [ ]:
param_grid = {
    'classifier__n_estimators': [100, 200, 300, 400],
    'classifier__max_depth': [None, 10, 20, 30],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4],
    'classifier__max_features': ['auto', 'sqrt', 'log2']
}

I wasn't sure which numbers to start off with in the param grid. After doing some research I found that the numbers entered above were "default" numbers for when you are unsure what parameters to set.

In [ ]:
grid = GridSearchCV(estimator=pipeline, param_grid=param_grid, 
                           scoring='accuracy', cv=5, n_jobs=-1, verbose=2) # Fit the model

grid.fit(x_train, y_train)

# Get the best parameters and evaluate
print("Best Parameters:", grid.best_params_)
print("Best Cross-validation Score:", grid.best_score_)

best_model = grid.best_estimator_
y_pred = best_model.predict(x_test)

In [ ]:
print("Testing accuracy:", best_model.score(x_test, y_test))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

trying again but using RandomizedSearchCV instead to see if i can get better results

In [ ]:
from sklearn.model_selection import StratifiedKFold

param_grid1 = {
    'classifier__n_estimators': [50, 100, 200, 300, 400, 500],
    'classifier__max_depth': [None, 10, 20, 30],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4],
    'classifier__max_features': ['sqrt', 'log2', None]  # Removed 'auto'
}


search = RandomizedSearchCV(pipeline, param_distributions=param_grid1, n_iter=100,
                            cv=StratifiedKFold(n_splits=3), scoring='f1_weighted',
                            random_state=42, n_jobs=-1)

In [ ]:
search.fit(x_train, y_train)

# Evaluate the best model
print("Best parameters found: ", search.best_params_)

In [ ]:
best_model = search.best_estimator_
best_model.fit(x_train, y_train)

# Evaluate on the test set
test_accuracy = best_model.score(x_test, y_test)
print(f"Test Accuracy: {test_accuracy:.2f}")

Next, I will use the best model to create a function that takes a single row of test data and predict the quality of wine.

In [ ]:
def wine_quality(row, best_model):
    result = best_model.predict(row)
    return result[0]

In [ ]:
sample_row = X.iloc[[16]]

predicted_quality = wine_quality(sample_row, best_model)

print(f"Predicted wine quality: {predicted_quality}")

After reevualating the assignment I realized I had to filter out the white wine rows from the dataset to focus on building a red wine quality classifier

In [24]:
white_count = original_data[original_data['color'] == 'white'].shape[0]
print(f"Number of rows with white wine: {white_count}")

Number of rows with white wine: 4898


In [26]:
data = original_data[original_data['color'] != 'white']

In [32]:
Xred = data.drop(columns=['quality'])  # Features
yred = data['quality']

In [34]:
Xred.shape, yred.shape

((1599, 12), (1599,))

In [40]:
xred_train, xred_test, yred_train, yred_test = train_test_split(Xred, 
                                                    yred,
                                                    test_size=0.3,
                                                    random_state=42)

In [44]:
xred_train.shape, xred_test.shape, yred_train.shape, yred_test.shape

((1119, 12), (480, 12), (1119,), (480,))

In [48]:
xred_test

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
803             7.7              0.56         0.08            2.50      0.114   
124             7.8              0.50         0.17            1.60      0.082   
350            10.7              0.67         0.22            2.70      0.107   
682             8.5              0.46         0.31            2.25      0.078   
1326            6.7              0.46         0.24            1.70      0.077   
...             ...               ...          ...             ...        ...   
1468            7.3              0.48         0.32            2.10      0.062   
495            10.7              0.35         0.53            2.60      0.070   
1325            6.7              0.46         0.24            1.70      0.077   
514            10.5              0.51         0.64            2.40      0.107   
576             9.9              0.50         0.24            2.30      0.103   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
803                  14.0                  46.0  0.99710  3.24       0.66   
124                  21.0                 102.0  0.99600  3.39       0.48   
350                  17.0                  34.0  1.00040  3.28       0.98   
682                  32.0                  58.0  0.99800  3.33       0.54   
1326                 18.0                  34.0  0.99480  3.39       0.60   
...                   ...                   ...      ...   ...        ...   
1468                 31.0                  54.0  0.99728  3.30       0.65   
495                   5.0                  16.0  0.99720  3.15       0.65   
1325                 18.0                  34.0  0.99480  3.39       0.60   
514                   6.0                  15.0  0.99730  3.09       0.66   
576                   6.0                  14.0  0.99780  3.34       0.52   

      alcohol color  
803       9.6   red  
124       9.5   red  
350       9.9   red  
682       9.8   red  
1326     10.6   red  
...       ...   ...  
1468     10.0   red  
495      11.0   red  
1325     10.6   red  
514      11.8   red  
576      10.0   red  

[480 rows x 12 columns]

In [52]:
pline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

In [54]:
pline.fit(xred_train, yred_train)
yred_pred = pline.predict(xred_test)

# Calculate and print the training and testing accuracies
print("Training accuracy :", pline.score(xred_train, yred_train))
print("Testing accuracy :", pline.score(xred_test, yred_test))

# Classification report
print("Classification Report:")
print(classification_report(yred_test, yred_pred))

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(yred_test, yred_pred))

Training accuracy : 1.0
Testing accuracy : 0.6625
Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        17
           5       0.73      0.78      0.76       195
           6       0.63      0.69      0.66       200
           7       0.54      0.44      0.49        61
           8       0.50      0.17      0.25         6

    accuracy                           0.66       480
   macro avg       0.40      0.35      0.36       480
weighted avg       0.63      0.66      0.65       480

Confusion Matrix:
[[  0   0   1   0   0   0]
 [  0   0  10   7   0   0]
 [  0   0 153  40   2   0]
 [  0   0  46 137  17   0]
 [  0   0   0  33  27   1]
 [  0   0   0   1   4   1]]


/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


These results are slightly worse than my mixed test. The F1 score with both red and white wine was .67. However, it's not much difference